name: Destroy Infrastucture
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production


    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout repostiory
      uses: actions/checkout@v4

    - name: Configuration AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::448049825151:role/IG-OIDC
        aws-region: ap-southeast-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    - name: Initialize Terraform
      run: terraform init

    - name: Destroy Infrastructure
      run: terraform destroy -auto-approve --var-file="variables/dev.tfvars"

